Feature/travis
MrAlejandro/TaskManager pull request #11
Opened 2019-03-26 10:22 UTC by MrAlejandro

2019-03-26 21:10 UTC, artempartos requested changes

2019-03-26 21:10 UTC, artempartos commented on README.md
> +[![Build Status](https://travis-ci.org/ElHexio/TaskManager.svg?branch=master)](https://travis-ci.org/ElHexio/TaskManager)
укажи девелоп ветку

2019-03-27 05:18 UTC, MrAlejandro commented on README.md
> +[![Build Status](https://travis-ci.org/ElHexio/TaskManager.svg?branch=master)](https://travis-ci.org/ElHexio/TaskManager)
done

2019-03-27 20:40 UTC, artempartos commented
Предпочтиительнее делать rebase, чтобы история оставалось красивой. Посмотри на списко коммитов и на код который добавлен. Можешь смержить, но я бы попробовал научиться делать stash, там например всегда требуют в опенсорсе
git rebase -i commit_hash

2019-03-27 20:41 UTC, artempartos commented
👍

2019-03-28 15:10 UTC, merged