Feature/admin area
MrAlejandro/TaskManager pull request #16
Opened 2019-03-30 10:47 UTC by MrAlejandro

2019-03-30 11:49 UTC, Andrew8xx8 requested changes

2019-03-30 11:49 UTC, Andrew8xx8 commented on app/models/user.rb
> +  def name
Метод лучше назвать `full_name`

2019-03-30 11:49 UTC, Andrew8xx8 commented on app/models/user.rb
> +  def name
Этот метод является логикой отображения, есть статья как такую логику лучше выносить
https://nithinbekal.com/posts/rails-presenters/

2019-03-30 11:49 UTC, Andrew8xx8 commented on config/routes.rb
> +    resources :users
Здесь необходимо указать те HTTP методы которые будут использоваться

2019-03-30 11:49 UTC, Andrew8xx8 commented on db/seeds.rb
> +  u.email = "email#{i}@mail.gen"
Лучше использовать `find_or_create` в фикстурах, чтобы можно было при случае запустить их еще раз. Повторный запуск сейчас приведет к ошибке валидации уникального email

2019-03-30 12:37 UTC, MrAlejandro commented on config/routes.rb
> +    resources :users
done

2019-03-30 12:54 UTC, MrAlejandro commented on db/seeds.rb
> +  u.email = "email#{i}@mail.gen"
done

2019-03-30 13:41 UTC, MrAlejandro commented on app/models/user.rb
> +  def name
done

2019-04-01 17:18 UTC, Andrew8xx8 approved these changes

2019-04-01 17:28 UTC, merged