Feature/kanban board
MrAlejandro/TaskManager pull request #18
Opened 2019-04-03 10:10 UTC by MrAlejandro

2019-04-04 14:27 UTC, artempartos requested changes

2019-04-04 14:27 UTC, artempartos commented on Makefile
> +	yarn install
лучше запускать install, lint и lint fix тоже внутри контейнера, так как на хост тачке например может быть другая нода или что-то еще

2019-04-04 16:15 UTC, MrAlejandro commented on Makefile
> +	yarn install
done

2019-04-08 10:39 UTC, artempartos commented
👍

2019-04-08 16:09 UTC, merged