Feature/tasks
MrAlejandro/TaskManager pull request #19
Opened 2019-04-06 14:24 UTC by MrAlejandro

2019-04-06 14:42 UTC, MrAlejandro commented
@MrAlejandro не забудь сменить базовую ветку при мерже.

2019-04-08 10:44 UTC, artempartos requested changes

2019-04-08 10:44 UTC, artempartos commented on app/javascript/packs/components/EditPopup.js
> +    if (this.props.cardId != null && this.props.cardId !== prevProps.cardId) {
думаю что этот колбек не надо использовать, достаточно просто нужный key передавать при рендере

2019-04-08 17:48 UTC, MrAlejandro commented on app/javascript/packs/components/EditPopup.js
> +    if (this.props.cardId != null && this.props.cardId !== prevProps.cardId) {
выпилил `componentDidUpdate`.

2019-04-08 18:57 UTC, artempartos commented
поменяй ветку на девелоп

2019-04-08 19:25 UTC, artempartos requested changes

2019-04-08 19:25 UTC, artempartos commented on app/javascript/packs/components/EditPopup.js
> +        this.setState({ task: data });
зачем нужны два сетСтейта? почему в одном не сделать?

2019-04-08 19:25 UTC, artempartos commented on app/javascript/packs/components/AddPopup.js
> +      if (response.status === STATUS_CREATED) {
не вынести ли такую обработку ошибки в fetchhelper, проверяя все запросы на успешность (2хх)? вроде даже аттрибут специиальный есть, называется ok

2019-04-09 16:09 UTC, MrAlejandro commented on app/javascript/packs/components/EditPopup.js
> +        this.setState({ task: data });
Переделал на один.

2019-04-10 09:24 UTC, MrAlejandro commented on app/javascript/packs/components/AddPopup.js
> +      if (response.status === STATUS_CREATED) {
Сделал, только странно получилось, но как улучшить пока не могу придумать.

2019-04-10 09:44 UTC, Andrew8xx8 commented
Тоже самое замечание, что и в соседнем PR. Использование `let`  без надобности. Также можно отрефакторить доступ к state через докунструкцию обёектов.
```
const { task } = this.state;
<div>{task.name}</div>
```

2019-04-11 16:10 UTC, Andrew8xx8 approved these changes

2019-04-11 16:34 UTC, merged