Feature/assignee
MrAlejandro/TaskManager pull request #20
Opened 2019-04-08 10:07 UTC by MrAlejandro

2019-04-08 10:46 UTC, artempartos requested changes

2019-04-08 10:46 UTC, artempartos commented on app/controllers/api/v1/application_controller.rb
> +  def build_meta_users(collection)
зачем тебе отдельная мета для юзеров?)

2019-04-08 10:46 UTC, artempartos commented on app/serializers/user_serializer.rb
> +  def id
зачем id делать строкой?)

2019-04-08 18:02 UTC, MrAlejandro commented on app/serializers/user_serializer.rb
> +  def id
да, это бесполезная штука, удалил.

2019-04-08 18:30 UTC, MrAlejandro commented on app/serializers/user_serializer.rb
> +  def id
Нашел где поломалось:
> Warning: Failed prop type: Invalid prop `id` of type `number` supplied to `Card`, expected `string`.
в методе `fetchLine` в 
```
    return fetch('GET', tasks_url)
      .then(({ data }) => data);
```
приходит json с `id` типа `number`, пока вернул на бэкенд конвертацию, мне кажет так удобнее, чем в отображении модифить.

2019-04-08 18:51 UTC, MrAlejandro commented on app/controllers/api/v1/application_controller.rb
> +  def build_meta_users(collection)
Там коллекция юзеров, не использует пагинацию, и падает при вызове специфичных методов. Я придумал одно решение, но оно мне не понравилось, поэтому я вернулся к отдельному методу. 

Я вернул костыльное решение, но оно мне, все еще, не нравится)

2019-04-08 18:56 UTC, artempartos commented on app/serializers/user_serializer.rb
> +  def id
Хм, странно что карточка ждет строку, ну ок

2019-04-08 19:26 UTC, artempartos commented on app/controllers/api/v1/application_controller.rb
> +  def build_meta_users(collection)
в этом и проблема, пагинация должна быть, это антипаттерн, вываливать всю базу, сделай пагинацию, с фронта шли например per_page 10, используй build_meta, который должен использоваться одинаковый во всем проекте

2019-04-08 20:02 UTC, artempartos requested changes

2019-04-08 20:02 UTC, artempartos commented on app/controllers/api/v1/users_controller.rb
> +              .ransack(q_params)
просто добавь сюда пагинацию, зачем тебе эти хаки с респонд ту?

2019-04-09 17:13 UTC, MrAlejandro commented on app/controllers/api/v1/application_controller.rb
> +  def build_meta_users(collection)
сделал пагинацию и единый метод.

2019-04-09 17:14 UTC, MrAlejandro commented on app/controllers/api/v1/users_controller.rb
> +              .ransack(q_params)
done.

2019-04-10 09:41 UTC, Andrew8xx8 requested changes

2019-04-10 09:41 UTC, Andrew8xx8 commented on app/javascript/packs/components/AddPopup.js
> +                value={this.state.task.name}
В начале метода достань `task`. и используй его потом. Код станет чище
```
const { task } = this.state;
<div>{task.name}</div>
```
В целом это хорошая практика в начале `reder` метода достать все нужное из `props` и `state` и использовать эти значения ниже, не доставая каждый раз через `this` и несколько точек

2019-04-10 09:41 UTC, Andrew8xx8 commented on app/javascript/packs/components/UserSelect.js
> +    let { first_name, last_name } = option;
Почему `let` здесть? Зачем использовать `let`, в чем разница с `const` и  `var`

2019-04-10 09:41 UTC, Andrew8xx8 commented on app/serializers/user_serializer.rb
> +  def id
ID должен быть числом, если нужно что-то во фронтенде конвертировать — то нужно это конвертировать именно в том месте где это нужно. А не менять формат API для того чтобы работала библиотека какая-то на фронтенде.
Библиотека может быть в любой момент изменена, а вот формат API поменять будет сложно, потому что появятся уже клиенты которые будут зависеть от этого формата.

2019-04-10 16:48 UTC, MrAlejandro commented on app/serializers/user_serializer.rb
> +  def id
перенес конвертацию в представление.

2019-04-10 17:01 UTC, MrAlejandro commented on app/javascript/packs/components/AddPopup.js
> +                value={this.state.task.name}
done

2019-04-10 17:07 UTC, MrAlejandro commented on app/javascript/packs/components/UserSelect.js
> +    let { first_name, last_name } = option;
`const` - нужен для того что бы нельзя было повторно присвоить значение.
`let` - наоборот позволяет присвоить значение повторно.
`var` - с точки зрения семантики непонятен (+ нет блочной области видимости, но есть hoisting).

Т.е. тут семантически правильно использовать `const` - исправил.

2019-04-11 16:10 UTC, Andrew8xx8 approved these changes

2019-04-11 16:35 UTC, merged